import { useState } from "react";
import { ArrowDown, ArrowUpRight, Bell, CalendarDays, Check, CircleDollarSign, CircleUserRound, FileText, FolderKanban, Heart, Layers, List, Mail, MoreHorizontal, Palette, Search, Settings2, SlidersHorizontal, ToggleRight, Upload } from "lucide-react";
import { ProjectCard } from "../components/ProjectCard";
import { templateProjects } from "../lib/template";

const palettes = {
	atelier: { label: "Atelier", accent: "#e45c45", accentDeep: "#b84232", sage: "#dce6d7", yellow: "#f3c969" },
	coastal: { label: "Coastal", accent: "#197b8c", accentDeep: "#0d5968", sage: "#d7e9e4", yellow: "#e8b75d" },
	orchard: { label: "Orchard", accent: "#71883f", accentDeep: "#50662c", sage: "#e1e8cf", yellow: "#d99e45" },
	ink: { label: "Ink", accent: "#7566a8", accentDeep: "#554682", sage: "#e4dfef", yellow: "#d6ad55" },
	rose: { label: "Rose", accent: "#b85d73", accentDeep: "#8f3d53", sage: "#f0dce1", yellow: "#e4b35d" },
	ember: { label: "Ember", accent: "#c56b31", accentDeep: "#95461f", sage: "#f0dfcf", yellow: "#e2b44e" },
	meadow: { label: "Meadow", accent: "#37846b", accentDeep: "#21614d", sage: "#d7e8dc", yellow: "#ddb85c" },
	blueprint: { label: "Blueprint", accent: "#3d6fa3", accentDeep: "#28527e", sage: "#d9e4f0", yellow: "#d8ac51" },
} as const;

type PaletteName = keyof typeof palettes;
export function ReferencePage({ eyebrow, title, copy }: { eyebrow: string; title: React.ReactNode; copy: string }) {
	const [palette, setPalette] = useState<PaletteName>("atelier");
	const colors = palettes[palette];
	const themeStyle = { "--library-accent": colors.accent, "--library-accent-deep": colors.accentDeep, "--library-sage": colors.sage, "--library-yellow": colors.yellow } as React.CSSProperties;
	return <main className="reference-page section-wrap" style={themeStyle}><div className="library-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-intro">{copy}</p></div><Palette size={22} /></div><div className="library-palette-picker" aria-label="Library color theme"><div><p className="eyebrow">Color theme</p><strong>Preview the system in a different voice.</strong></div><div className="palette-options">{(Object.keys(palettes) as PaletteName[]).map((name) => <button key={name} className={palette === name ? "palette-option active" : "palette-option"} onClick={() => setPalette(name)}><i style={{ background: palettes[name].accent }} /><span>{palettes[name].label}</span></button>)}</div></div><div className="library-grid">
		<LibraryPanel icon={<Layers size={19} />} label="Buttons" title="Clear actions, at every level."><div className="library-button-row"><button className="button button-library-primary">Primary action <ArrowUpRight size={14} /></button><button className="button button-library-secondary">Secondary</button><button className="button button-library-tertiary">Tertiary</button></div><div className="library-button-row"><button className="icon-button library-icon-button" aria-label="Like"><Heart size={16} /></button><button className="icon-button library-icon-button" aria-label="More"><MoreHorizontal size={16} /></button><button className="button button-library-primary" disabled>Disabled</button></div></LibraryPanel>
		<LibraryPanel icon={<Bell size={19} />} label="Inbox list cards" title="Tabs, filters, and useful updates."><div className="library-pills" role="tablist"><button className="active" role="tab">Notifications</button><button role="tab">History</button></div><div className="library-pills library-filters" role="group"><button className="active">All</button><button>Projects</button><button>Donations</button></div><div className="library-notification-list"><article className="library-notification-card unread"><span className="library-card-icon"><FolderKanban size={17} /></span><div><strong>North Star workspace reached 75%</strong><small>Today, 9:42 AM</small><p>The project is getting close to its funding goal.</p></div><span className="library-card-meta">Unread</span></article><article className="library-notification-card"><span className="library-card-icon donation"><CircleDollarSign size={17} /></span><div><strong>Donation recorded</strong><small>Yesterday, 4:18 PM</small><p>Your support helped Open table dinners move forward.</p></div><Check size={15} className="library-card-meta" /></article></div></LibraryPanel>
		<LibraryPanel icon={<List size={19} />} label="Lists & pills" title="Useful density, gentle hierarchy."><div className="library-list"><div><span className="library-number">01</span><strong>Primary content item</strong><span className="library-pill success">Active</span><Check size={15} /></div><div><span className="library-number">02</span><strong>Secondary content item</strong><span className="library-pill">Draft</span><ArrowUpRight size={15} /></div><div><span className="library-number">03</span><strong>Archived content item</strong><span className="library-pill muted">Closed</span><FileText size={15} /></div></div></LibraryPanel>
		<LibraryPanel icon={<Layers size={19} />} label="Project catalog cards" title="Images, progress, and a clear next step."><div className="library-catalog-toolbar"><div className="library-pills" role="tablist"><button className="active" role="tab">All projects</button><button role="tab">Spaces</button><button role="tab">Programs</button></div><label className="library-search"><Search size={14} /><input placeholder="Search projects" aria-label="Search projects" /></label></div><div className="library-project-grid">{templateProjects.slice(0, 2).map((project, index) => <ProjectCard key={project.id} project={project} index={index} onDetails={() => undefined} onDonate={() => undefined} />)}</div></LibraryPanel>
		<LibraryPanel icon={<SlidersHorizontal size={19} />} label="Inputs & dropdowns" title="Quiet fields that invite focus."><div className="library-form-grid"><label>Search<label className="library-input"><Search size={14} /><input placeholder="Search projects" /></label></label><label>Category<select defaultValue="Programs"><option>Programs</option><option>Spaces</option><option>Tools</option></select></label><label className="library-form-wide">Message<textarea placeholder="Write a short note..." /></label></div></LibraryPanel>
		<LibraryPanel icon={<CalendarDays size={19} />} label="Calendar" title="A small view of time."><div className="library-calendar"><div className="calendar-header"><strong>September 2026</strong><span><button aria-label="Previous month"><ArrowUpRight size={13} /></button><button aria-label="Next month"><ArrowDown size={13} /></button></span></div><div className="calendar-week">{["M", "T", "W", "T", "F", "S", "S"].map((day, index) => <span key={`${day}-${index}`}>{day}</span>)}</div><div className="calendar-days">{Array.from({ length: 30 }, (_, index) => <button key={index} className={index + 1 === 18 ? "selected" : index + 1 === 24 ? "marked" : ""}>{index + 1}</button>)}</div></div></LibraryPanel>
		<LibraryPanel icon={<Upload size={19} />} label="Uploads" title="Bring your own material."><label className="upload-box library-upload"><Upload size={22} /><strong>Drop files here or choose files</strong><small>Images, documents, or media</small><input type="file" /></label></LibraryPanel>
		<LibraryPanel icon={<ToggleRight size={19} />} label="Toggles & tabs" title="Small switches, strong signals."><div className="library-switch-row"><div><strong>Email notifications</strong><small>Get updates about activity</small></div><button className="library-switch on" aria-label="Email notifications enabled"><span /></button></div><div className="library-tabs" role="tablist"><button className="active" role="tab">Overview</button><button role="tab">Activity</button><button role="tab">Settings</button></div></LibraryPanel>
		<LibraryPanel icon={<Palette size={19} />} label="Type, icons & status" title="The small things set the tone."><div className="library-type-sample"><span className="type-display">DM Serif Display</span><span className="type-body">Manrope / 10px labels / 14px body</span></div><div className="library-icon-row"><span><Bell size={17} /></span><span><Mail size={17} /></span><span><Settings2 size={17} /></span><span><CircleUserRound size={17} /></span><span className="library-status-dot" /></div></LibraryPanel>
	</div></main>;
}

function LibraryPanel({ icon, label, title, children }: { icon: React.ReactNode; label: string; title: string; children: React.ReactNode }) { return <article className="reference-panel library-panel">{icon}<p className="eyebrow">{label}</p><h2>{title}</h2>{children}</article>; }
